apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: curl
  name: curl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - image: rstarmer/curl:v1
        imagePullPolicy: IfNotPresent
        name: curl
      dnsPolicy: ClusterFirst
